-- CABS_FACTURAS

CREATE TABLE  "CABS_FACTURAS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FECHA" DATE, 
	"TIPO_CAB" NUMBER, 
	"PUNTO_VENTA" NUMBER(*,0), 
	"NRO_CAB" NUMBER(*,0), 
	"CUIT" VARCHAR2(11), 
	"DFISCAL" VARCHAR2(30), 
	"TOTAL_OPERACION" NUMBER(*,2), 
	"TOTAL_NO_GRAVADO" NUMBER(*,2), 
	"NETO_GRAVADO" NUMBER(*,2), 
	"IMPUESTO_1" NUMBER(*,2), 
	"IMPUESTO_2" NUMBER(*,2), 
	"IMPORTE_OPER_EXENTAS" NUMBER(*,2), 
	"IMPORTE_PERCEP_NAC" NUMBER(*,2), 
	"IMPORTE_PERCEP_IIBB" NUMBER(*,2), 
	"IMPORTE_PERCEP_MUNI" NUMBER(*,2), 
	"IMPORTE_IMP_INTERNOS" NUMBER(*,2), 
	"CAI" VARCHAR2(14), 
	 CONSTRAINT "CABS_FACTURAS_PK" PRIMARY KEY ("ID") ENABLE
   )
/

CREATE UNIQUE INDEX  "CABS_FACTURAS_IDX1" ON  "CABS_FACTURAS" ("TIPO_CAB", "PUNTO_VENTA", "NRO_CAB")
/

CREATE UNIQUE INDEX  "CABS_FACTURAS_IDX2" ON  "CABS_FACTURAS" ("CAI")
/

CREATE OR REPLACE TRIGGER  "CABS_FACTURAS_TRG" 
BEFORE INSERT ON CABS_FACTURAS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CABS_FACTURAS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER  "CABS_FACTURAS_TRG" ENABLE
/

-- CABS_FACTURAS_DETALLE

CREATE TABLE  "CABS_FACTURAS_DETALLE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CAB" NUMBER, 
	"FECHA" DATE, 
	"TIPO_CAB" NUMBER, 
	"PUNTO_VENTA" NUMBER, 
	"NRO_CAB" NUMBER, 
	"CANTIDAD" NUMBER(*,2), 
	"UNIDAD" VARCHAR2(2), 
	"PRECIO" NUMBER(*,2), 
	"BONIFICACION" NUMBER(*,2), 
	"AJUSTE" NUMBER(*,2), 
	"SUBTOTAL" NUMBER(*,2), 
	"IVA" NUMBER(*,2), 
	"MODO" VARCHAR2(1), 
	"ANULADO" VARCHAR2(1), 
	"TEXTO" VARCHAR2(75), 
	 CONSTRAINT "CABS_FACTURAS_DETA_ID_PK" PRIMARY KEY ("ID") ENABLE
   )
/
ALTER TABLE  "CABS_FACTURAS_DETALLE" ADD CONSTRAINT "CABS_FACTURAS_DETA_ID_CAB_FK" FOREIGN KEY ("ID_CAB")
	  REFERENCES  "CABS_FACTURAS" ("ID") ON DELETE CASCADE ENABLE
/

CREATE INDEX  "CABS_FACTURAS_DETALLE_I1" ON  "CABS_FACTURAS_DETALLE" ("ID_CAB")
/

CREATE OR REPLACE TRIGGER  "CABS_FACTURAS_DETALLE_TRG" 
BEFORE INSERT ON CABS_FACTURAS_DETALLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CABS_FACTURAS_DETALLE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER  "CABS_FACTURAS_DETALLE_TRG" ENABLE
/
