CREATE TABLE  "BOB_ESTADO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(20), 
	 CONSTRAINT "BOB_ESTADO_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "BOB_PROV" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROV" VARCHAR2(30) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_FEC" DATE, 
	"ACTIVO" VARCHAR2(1), 
	"DIAMETRO" NUMBER, 
	 CONSTRAINT "BOB_PROV_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "BOB_ORDEN" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROV" NUMBER, 
	"REMITO" NUMBER, 
	"FECHA" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	 CONSTRAINT "BOB_ORDEN_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "BOB_TIPO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"KEY" CHAR(1) NOT NULL ENABLE, 
	"TIPO_PAPEL" VARCHAR2(20) NOT NULL ENABLE, 
	"BACK_COLOR" NUMBER, 
	"FORE_COLOR" NUMBER, 
	"GRAMAJE_INI" NUMBER, 
	"STYLE" VARCHAR2(20), 
	"PRECIO_ACTUAL" NUMBER, 
	 CONSTRAINT "BOB_TIPO_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "BOB" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TIPO" NUMBER NOT NULL ENABLE, 
	"FORMATO" NUMBER NOT NULL ENABLE, 
	"GRAMAJE" NUMBER NOT NULL ENABLE, 
	"PESO" NUMBER NOT NULL ENABLE, 
	"DIAMETRO" NUMBER, 
	"PSTOCK" NUMBER DEFAULT 100 NOT NULL ENABLE, 
	"ESTADO" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_FEC" DATE, 
	"ORDEN_INGRESO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BOB_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "BOB_LUGAR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"LUGAR" VARCHAR2(20), 
	"KEY" VARCHAR2(1), 
	 CONSTRAINT "BOB_LUGAR_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "BOB_USO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FECHA" DATE, 
	"LUGAR" NUMBER, 
	"ORDEN" NUMBER, 
	"BOBINA" NUMBER, 
	"INICIO" NUMBER, 
	"FIN" NUMBER, 
	"USO" NUMBER, 
	"REND" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	 CONSTRAINT "BOB_USO_PK" PRIMARY KEY ("ID") ENABLE
   )
/
ALTER TABLE  "BOB" ADD CONSTRAINT "BOB_ESTADO_FK" FOREIGN KEY ("ESTADO")
	  REFERENCES  "BOB_ESTADO" ("ID") ENABLE
/
ALTER TABLE  "BOB" ADD CONSTRAINT "BOB_ORDEN_FK" FOREIGN KEY ("ORDEN_INGRESO")
	  REFERENCES  "BOB_ORDEN" ("ID") ENABLE
/
ALTER TABLE  "BOB_ORDEN" ADD CONSTRAINT "BOB_PROV_FK" FOREIGN KEY ("PROV")
	  REFERENCES  "BOB_PROV" ("ID") ENABLE
/
ALTER TABLE  "BOB" ADD CONSTRAINT "BOB_TIPO_FK" FOREIGN KEY ("TIPO")
	  REFERENCES  "BOB_TIPO" ("ID") ENABLE
/
ALTER TABLE  "BOB_USO" ADD CONSTRAINT "BOB_USO_FK" FOREIGN KEY ("BOBINA")
	  REFERENCES  "BOB" ("ID") ENABLE
/
ALTER TABLE  "BOB_USO" ADD CONSTRAINT "BOB_USO_LUGAR_FK" FOREIGN KEY ("LUGAR")
	  REFERENCES  "BOB_LUGAR" ("ID") ENABLE
/
