SELECT 
    ART.ID,
	ART_PKG.SCODIGO(ART.ID) CODIGO,
    ART.CLIENTE,
    LARGO,
	ANCHO,
	ALTO,
    CALIDAD,
	ART_PKG.CALIDAD_STYLE(CALIDAD) AS calidad_style,
    PLARGO,
	PANCHO,
	TRAZADOS,
    CASE WHEN V.PLANCHAS = 0 THEN NULL
		ELSE PLANCHAS END PLANCHAS,
    CASE WHEN V.PRODUCCION = 0 THEN NULL 
		ELSE PRODUCCION END PRODUCCION,
    V.PROCESO, 
    V.IDCAB TERM_ID,
    CASE WHEN V.CAJAS = 0 THEN NULL
		ELSE V.CAJAS END TERMINADO,
    CASE V.MODO WHEN 2 THEN 'sin_contar' 
		WHEN 1 THEN 'contado_ok' 
		ELSE '' END CONTADO_STYLE,
    PROD_PKG.PEDIDO(ART.ID) PEDIDO,
    (V.CAJAS + V.PRODUCCION) * art_pkg.superficie(art.id) M2,
	(V.CAJAS + V.PRODUCCION)/pallet_pkg.medida_pallet(art.id,'CANT_CAJAS') pallet
FROM VIEW_STOCK_GRAL V LEFT JOIN ART
    ON V.ART = ART.ID