CREATE TABLE  "ART_PROVEDOR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(200) NOT NULL ENABLE, 
	 CONSTRAINT "ART_PROVEDOR_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "ART_CALIDAD" 
   (	"ID" NUMBER(10,0), 
	"CODIGO" CHAR(10 CHAR), 
	"NOMBRE" CHAR(50 CHAR) NOT NULL ENABLE, 
	"IS_CORR" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"PAPEL_A" NUMBER, 
	"PAPEL_B" NUMBER, 
	"PAPEL_C" NUMBER, 
	"GRAM_A" NUMBER, 
	"GRAM_B" NUMBER, 
	"GRAM_C" NUMBER, 
	"CREATED_BY" VARCHAR2(200), 
	"CREATED_FEC" DATE, 
	"UPDATED_BY" VARCHAR2(200), 
	"UPDATED_FEC" DATE, 
	"ID_PROVEEDOR" NUMBER, 
	"COSTO_PROVEEDOR" NUMBER, 
	"STYLE" VARCHAR2(200), 
	"IS_DT" NUMBER, 
	"PESOM2" NUMBER, 
	 CONSTRAINT "ART_CALIDAD_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "ART_ESTADO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(20), 
	"STYLE" VARCHAR2(30), 
	 CONSTRAINT "ART_ESTADO_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "ART_GRUPOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CLIENTE" NUMBER, 
	"GRUPO" VARCHAR2(20), 
	 CONSTRAINT "ART_GRUPOS_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "ART_TIPO" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(20) NOT NULL ENABLE, 
	"ALETA_SUP" NUMBER, 
	"ALETA_INF" NUMBER, 
	"CIERRE" NUMBER, 
	"REFILE" NUMBER, 
	"CHAPETON" NUMBER, 
	 CONSTRAINT "VC_ARTICULOS_TIPO_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "ART" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"REV" NUMBER(*,0), 
	"CLIENTE" NUMBER(*,0), 
	"CODIGO" VARCHAR2(50), 
	"STATUS" NUMBER(*,0), 
	"TIPO" NUMBER(*,0), 
	"LARGO" NUMBER(*,0) DEFAULT NULL, 
	"ANCHO" NUMBER(*,0) DEFAULT NULL, 
	"ALTO" NUMBER(*,0) DEFAULT NULL, 
	"CALIDAD" NUMBER(*,0), 
	"PLARGO" NUMBER(*,0) DEFAULT NULL, 
	"PANCHO" NUMBER DEFAULT NULL, 
	"OBS" VARCHAR2(400), 
	"CREATED_FEC" DATE, 
	"CREATED_BY" VARCHAR2(200), 
	"UPDATED_FEC" DATE, 
	"UPDATED_BY" VARCHAR2(200), 
	"MULT_X" NUMBER(*,0) DEFAULT 1, 
	"MULT_Y" NUMBER(*,0) DEFAULT 1, 
	"DESARROLLO" NUMBER(*,0), 
	"CIERRE_TIPO" NUMBER(*,0), 
	"CIERRE_VALOR" NUMBER(*,0), 
	"ALETA_SUP_TIPO" NUMBER(*,0), 
	"ALETA_SUP_VALOR" NUMBER(*,0), 
	"ALETA_INF_TIPO" NUMBER(*,0), 
	"ALETA_INF_VALOR" NUMBER(*,0), 
	"CENTRO" NUMBER, 
	"MULT" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"REFILE" NUMBER DEFAULT NULL, 
	"COLOR" VARCHAR2(200), 
	"CORTANTE" NUMBER, 
	"TRAZADOS" VARCHAR2(200), 
	"SLOTTER" VARCHAR2(200), 
	"ESCALA" NUMBER(*,2) DEFAULT 1, 
	"GRUPO" NUMBER, 
	"AJ_PRECIO" NUMBER, 
	"PRECIO_ACTUAL" NUMBER, 
	"PRECIO_FEC" DATE, 
	"PRECIO_USER" VARCHAR2(20), 
	"CALCULAR" NUMBER DEFAULT 1, 
	"PRIORIDAD" NUMBER, 
	"PAQUETE" NUMBER, 
	"PALLET" NUMBER, 
	"SUNCHOS" NUMBER, 
	"IMAGEN" BLOB, 
	"MIMETYPE" VARCHAR2(40), 
	"FILENAME" VARCHAR2(200), 
	"PALLET_MODO" NUMBER, 
	"PALLET_BASE_ALTO" NUMBER, 
	"PALLET_VERT_ALTO" NUMBER, 
	"PALLET_VERT_FILA" NUMBER, 
	"PALLET_ESQUINERO" NUMBER, 
	 CONSTRAINT "ART_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "ART_MULT_NOT_ZERO" CHECK ( "MULT" >0) ENABLE
   )
/
CREATE TABLE  "ART_ALETAS" 
   (	"TIPO_ART" NUMBER NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"ALETA" VARCHAR2(20), 
	"VALOR" NUMBER, 
	 CONSTRAINT "ART_ALETAS_PK" PRIMARY KEY ("TIPO_ART", "ID") ENABLE
   )
/
CREATE TABLE  "ART_CIERRE" 
   (	"TIPO_ART" NUMBER NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"CIERRE" VARCHAR2(20), 
	"VALOR" NUMBER, 
	 CONSTRAINT "ART_CIERRE_PK" PRIMARY KEY ("TIPO_ART", "ID") ENABLE
   )
/
CREATE TABLE  "ART_COLOR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" NVARCHAR2(200) NOT NULL ENABLE, 
	"COLOR_HTML" NVARCHAR2(200) NOT NULL ENABLE, 
	"PANTONE" NVARCHAR2(200), 
	 CONSTRAINT "VC_ARTICULOS_COLOR_PK1" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "ART_DESARROLLO" 
   (	"TIPO_ART" NUMBER NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"DESARROLLO" VARCHAR2(20), 
	 CONSTRAINT "ART_DESARROLLO_PK" PRIMARY KEY ("TIPO_ART", "ID") ENABLE
   )
/
CREATE TABLE  "ART_ESPECIAL" 
   (	"ID" NUMBER, 
	"ART_ID" NUMBER NOT NULL ENABLE, 
	"PART_ID" NUMBER NOT NULL ENABLE, 
	"CANT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ART_ESPECIAL_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "ART_PALLET" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"BASE" NUMBER, 
	"VERT" NUMBER, 
	"DETALLE" VARCHAR2(20), 
	"IMAGEN" BLOB, 
	"FILENAME" VARCHAR2(50), 
	"MIMETYPE" VARCHAR2(20), 
	"LASTUPD" DATE, 
	 CONSTRAINT "ART_PALLET_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "ART_PRIORIDAD" 
   (	"ID" NUMBER, 
	"NOMBRE" NVARCHAR2(20)
   )
/
ALTER TABLE  "ART" ADD CONSTRAINT "ART_CALIDAD" FOREIGN KEY ("CALIDAD")
	  REFERENCES  "ART_CALIDAD" ("ID") ENABLE
/
ALTER TABLE  "ART" ADD CONSTRAINT "ART_CLI" FOREIGN KEY ("CLIENTE")
	  REFERENCES  "CLI" ("ID") ENABLE
/
ALTER TABLE  "ART_ESPECIAL" ADD CONSTRAINT "ART_ESPECIAL_FK1" FOREIGN KEY ("ART_ID")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "ART_ESPECIAL" ADD CONSTRAINT "ART_ESPECIAL_FK2" FOREIGN KEY ("PART_ID")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "ART" ADD CONSTRAINT "ART_STATUS" FOREIGN KEY ("STATUS")
	  REFERENCES  "ART_ESTADO" ("ID") ENABLE
/
ALTER TABLE  "ART" ADD CONSTRAINT "ART_TIPO" FOREIGN KEY ("TIPO")
	  REFERENCES  "ART_TIPO" ("ID") ENABLE
/
ALTER TABLE  "ART" ADD CONSTRAINT "FK_ART_GRUPO" FOREIGN KEY ("GRUPO")
	  REFERENCES  "ART_GRUPOS" ("ID") ON DELETE SET NULL ENABLE
/
ALTER TABLE  "ART_CALIDAD" ADD FOREIGN KEY ("PAPEL_A")
	  REFERENCES  "BOB_TIPO" ("ID") ENABLE
/
ALTER TABLE  "ART_CALIDAD" ADD FOREIGN KEY ("PAPEL_B")
	  REFERENCES  "BOB_TIPO" ("ID") ENABLE
/
ALTER TABLE  "ART_CALIDAD" ADD FOREIGN KEY ("PAPEL_C")
	  REFERENCES  "BOB_TIPO" ("ID") ENABLE
/
ALTER TABLE  "ART_CALIDAD" ADD FOREIGN KEY ("ID_PROVEEDOR")
	  REFERENCES  "ART_PROVEDOR" ("ID") ENABLE
/
