CREATE TABLE  "CABS_CORR_C" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ART_1" NUMBER, 
	"CANT_1" NUMBER, 
	"MULT_1" NUMBER, 
	"CAL_1" NUMBER, 
	"LARGO_1" NUMBER, 
	"ONDA_1" NUMBER, 
	"TRAZ_1" VARCHAR2(200), 
	"ART_2" NUMBER, 
	"CANT_2" NUMBER, 
	"MULT_2" NUMBER, 
	"CAL_2" NUMBER, 
	"LARGO_2" NUMBER, 
	"ONDA_2" NUMBER, 
	"TRAZ_2" VARCHAR2(200), 
	"ART_3" NUMBER, 
	"CANT_3" NUMBER, 
	"MULT_3" NUMBER, 
	"CAL_3" NUMBER, 
	"LARGO_3" NUMBER, 
	"ONDA_3" NUMBER, 
	"TRAZ_3" VARCHAR2(200), 
	"CALIDAD" NUMBER, 
	"FORMATO" NUMBER, 
	"ESTADO" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"MX_1" NUMBER, 
	"MX_2" NUMBER, 
	"MX_3" NUMBER, 
	 CONSTRAINT "CABS_CORR_C_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_CORR_D" 
   (	"FECHA" DATE, 
	"ORDEN" NUMBER, 
	"ID" NUMBER NOT NULL ENABLE, 
	"ART_1" NUMBER, 
	"CANT_1" NUMBER, 
	"ART_2" NUMBER, 
	"CANT_2" NUMBER, 
	"ART_3" NUMBER, 
	"CANT_3" NUMBER, 
	"PLARGO_1" NUMBER, 
	"PLARGO_2" NUMBER, 
	"PLARGO_3" NUMBER, 
	"ONDA_1" NUMBER, 
	"ONDA_2" NUMBER, 
	"ONDA_3" NUMBER, 
	"TRAZADOS_1" VARCHAR2(200), 
	"CALIDAD" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"TRAZADOS_2" VARCHAR2(200), 
	"TRAZADOS_3" VARCHAR2(200), 
	"FORMATO" VARCHAR2(20), 
	"MULT_1" NUMBER, 
	"MULT_2" NUMBER, 
	"MULT_3" NUMBER, 
	"ID_CORR" NUMBER, 
	"MX_1" NUMBER, 
	"MX_2" NUMBER, 
	"MX_3" NUMBER, 
	"ESTADO" NUMBER, 
	 CONSTRAINT "CABS_CORR_D_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_CORR_D_IMPORT" 
   (	"FECHA" DATE, 
	"ORDEN" NUMBER, 
	"ID" NUMBER NOT NULL ENABLE, 
	"ART_1" NUMBER, 
	"CANT_1" NUMBER, 
	"ART_2" NUMBER, 
	"CANT_2" NUMBER, 
	"ART_3" NUMBER, 
	"CANT_3" NUMBER, 
	"PLARGO_1" NUMBER, 
	"PLARGO_2" NUMBER, 
	"PLARGO_3" NUMBER, 
	"ONDA_1" NUMBER, 
	"ONDA_2" NUMBER, 
	"ONDA_3" NUMBER, 
	"TRAZADOS_1" VARCHAR2(200), 
	"CALIDAD" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"TRAZADOS_2" VARCHAR2(200), 
	"TRAZADOS_3" VARCHAR2(200), 
	"FORMATO" VARCHAR2(20), 
	"MULT_1" NUMBER, 
	"MULT_2" NUMBER, 
	"MULT_3" NUMBER, 
	"ID_CORR" NUMBER, 
	"MX_1" NUMBER, 
	"MX_2" NUMBER, 
	"MX_3" NUMBER, 
	"ESTADO" NUMBER
   )
/
CREATE TABLE  "CABS_CORR_EXT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROV" NUMBER, 
	"ART" NUMBER, 
	"CANT" NUMBER, 
	"PLARGO" NUMBER, 
	"ONDA" NUMBER, 
	"TRAZADOS" VARCHAR2(20), 
	"CALIDAD" NUMBER, 
	"FECHA" DATE, 
	"PRECIO" NUMBER, 
	"REMITO" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"ESTADO" NUMBER, 
	"FEC_PEDIDO" DATE, 
	 CONSTRAINT "CABS_CORR_EXT_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_CORR_FAV" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ART_1" NUMBER, 
	"CANT_1" NUMBER, 
	"MULT_1" NUMBER, 
	"CAL_1" NUMBER, 
	"LARGO_1" NUMBER, 
	"ONDA_1" NUMBER, 
	"TRAZ_1" VARCHAR2(200), 
	"ART_2" NUMBER, 
	"CANT_2" NUMBER, 
	"MULT_2" NUMBER, 
	"CAL_2" NUMBER, 
	"LARGO_2" NUMBER, 
	"ONDA_2" NUMBER, 
	"TRAZ_2" VARCHAR2(200), 
	"ART_3" NUMBER, 
	"CANT_3" NUMBER, 
	"MULT_3" NUMBER, 
	"CAL_3" NUMBER, 
	"LARGO_3" NUMBER, 
	"ONDA_3" NUMBER, 
	"TRAZ_3" VARCHAR2(200), 
	"CALIDAD" NUMBER, 
	"FORMATO" NUMBER, 
	"ESTADO" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"MX_1" NUMBER, 
	"MX_2" NUMBER, 
	"MX_3" NUMBER, 
	 CONSTRAINT "CABS_CORR_FAV_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_ENTREGAS_M" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	"CLIENTE" NUMBER NOT NULL ENABLE, 
	"IIBB" NUMBER(*,4), 
	"SUBT_IVA" NUMBER(*,4), 
	"TOTAL" NUMBER(*,4), 
	"REMITO" NUMBER NOT NULL ENABLE, 
	"FACTURA" NUMBER, 
	"DFISCAL" NUMBER, 
	"MODO" NUMBER NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"SUBT_NETO" NUMBER, 
	"DEPOSITO" NUMBER, 
	"SUBT_IIBB" NUMBER, 
	"STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"ID_VIAJE" NUMBER, 
	"NOTAS" VARCHAR2(400), 
	 CONSTRAINT "CABS_ENTREGAS_M_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "NRO_REMITO" UNIQUE ("REMITO") ENABLE
   )
/
CREATE TABLE  "CABS_PEDIDOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CLIENTE" NUMBER, 
	"ART_ID" NUMBER, 
	"PRECIO" NUMBER(*,4), 
	"ORDEN_COMPRA" VARCHAR2(20), 
	"FECHA_PED" DATE, 
	"FECHA_ENT" DATE, 
	"OBS" VARCHAR2(200), 
	"STATUS" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"FAC_TO" NUMBER, 
	"ENT_EN" NUMBER, 
	"CANT" NUMBER, 
	 CONSTRAINT "VC_PEDIDOS_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_ENTREGAS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CAB" NUMBER NOT NULL ENABLE, 
	"ART" NUMBER, 
	"CANT" NUMBER, 
	"PRECIO" NUMBER(*,4), 
	"IVA" NUMBER(*,4), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"DETALLE" VARCHAR2(40), 
	"PEDIDO" NUMBER, 
	 CONSTRAINT "VC_ENTREGAS_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_ENTREGAS_M2" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	"CLIENTE" NUMBER NOT NULL ENABLE, 
	"SUBT_NETO" NUMBER, 
	"TOTAL" NUMBER(*,4), 
	"REMITO" NUMBER, 
	"DEPOSITO" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"NOTAS" VARCHAR2(400), 
	 CONSTRAINT "CABS_ENTREGAS_M2_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "NRO_REMIRO2" UNIQUE ("REMITO") ENABLE
   )
/
CREATE TABLE  "CABS_ENTREGAS_2" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CAB" NUMBER NOT NULL ENABLE, 
	"ART" NUMBER, 
	"CANT" NUMBER, 
	"PRECIO" NUMBER(*,4), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"DETALLE" VARCHAR2(40), 
	"PEDIDO" NUMBER, 
	 CONSTRAINT "VC_ENTREGAS2_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_FACTURAS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FECHA" DATE, 
	"TIPO_CAB" NUMBER, 
	"PUNTO_VENTA" NUMBER(*,0), 
	"NRO_CAB" NUMBER(*,0), 
	"CUIT" VARCHAR2(11), 
	"DFISCAL" VARCHAR2(80), 
	"TOTAL_OPERACION" NUMBER(*,2), 
	"TOTAL_NO_GRAVADO" NUMBER(*,2), 
	"NETO_GRAVADO" NUMBER(*,2), 
	"IMPUESTO_1" NUMBER(*,2), 
	"IMPUESTO_2" NUMBER(*,2), 
	"IMPORTE_OPER_EXENTAS" NUMBER(*,2), 
	"IMPORTE_PERCEP_NAC" NUMBER(*,2), 
	"IMPORTE_PERCEP_IIBB" NUMBER(*,2), 
	"IMPORTE_PERCEP_MUNI" NUMBER(*,2), 
	"IMPORTE_IMP_INTERNOS" NUMBER(*,2), 
	"CAI" VARCHAR2(14), 
	 CONSTRAINT "CABS_FACTURAS_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_FACTURAS_DETALLE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CAB" NUMBER, 
	"FECHA" DATE, 
	"TIPO_CAB" NUMBER, 
	"PUNTO_VENTA" NUMBER, 
	"NRO_CAB" NUMBER, 
	"CANTIDAD" NUMBER(*,2), 
	"UNIDAD" VARCHAR2(2), 
	"PRECIO" NUMBER(*,2), 
	"BONIFICACION" NUMBER(*,2), 
	"AJUSTE" NUMBER(*,2), 
	"SUBTOTAL" NUMBER(*,2), 
	"IVA" NUMBER(*,2), 
	"MODO" VARCHAR2(1), 
	"ANULADO" VARCHAR2(1), 
	"TEXTO" VARCHAR2(75), 
	 CONSTRAINT "CABS_FACTURAS_DETA_ID_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_TERM" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ART" NUMBER, 
	"CANT" NUMBER, 
	"ESTADO" NUMBER, 
	"PEDIDO" NUMBER, 
	"FECHA" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"ART_PL" NUMBER, 
	"CANT_PL" NUMBER, 
	"CONTADO_BY" VARCHAR2(20), 
	"CONTADO_FEC" DATE, 
	"ART_TIPO" NUMBER, 
	"ART_MULT" NUMBER, 
	"NOTAS" VARCHAR2(200), 
	 CONSTRAINT "CABS_TERMINADO_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_TERM_ESTADO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROCESO" VARCHAR2(20), 
	 CONSTRAINT "CABS_TERM_ESTADO_ID_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_TERM_ORIGEN" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CORR" NUMBER, 
	"ID_TERM" NUMBER, 
	"ART" NUMBER, 
	"CANT_PL" NUMBER, 
	"IT_CORR" NUMBER, 
	 CONSTRAINT "CABS_TERM_ORIGEN_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_TERM_PROC" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_TERM" NUMBER, 
	"ORDEN" NUMBER, 
	"TIPO_PROC" NUMBER, 
	"FECHA" NUMBER, 
	"MAQ" NUMBER, 
	"PERSONAL" NUMBER, 
	"OBS" VARCHAR2(200), 
	 CONSTRAINT "CABS_TERM_PROC_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CABS_VIAJES_M" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CAMION" NUMBER, 
	"FECHA" DATE, 
	"ESTADO" NUMBER, 
	"CREATED_BY" NVARCHAR2(20), 
	"CREATED_FEC" DATE, 
	 CONSTRAINT "CABS_VIAJES_M_PK" PRIMARY KEY ("ID") ENABLE
   )
/
ALTER TABLE  "CABS_FACTURAS_DETALLE" ADD CONSTRAINT "CABS_FACTURAS_DETA_ID_CAB_FK" FOREIGN KEY ("ID_CAB")
	  REFERENCES  "CABS_FACTURAS" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "CABS_CORR_D" ADD CONSTRAINT "FK_CORR_C_D" FOREIGN KEY ("ID_CORR")
	  REFERENCES  "CABS_CORR_C" ("ID") DISABLE
/
ALTER TABLE  "CABS_ENTREGAS" ADD CONSTRAINT "FK_ENTREGAS" FOREIGN KEY ("ID_CAB")
	  REFERENCES  "CABS_ENTREGAS_M" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS_2" ADD CONSTRAINT "FK_ENTREGAS_2" FOREIGN KEY ("ID_CAB")
	  REFERENCES  "CABS_ENTREGAS_M2" ("ID") ENABLE
/
ALTER TABLE  "CABS_TERM_ORIGEN" ADD CONSTRAINT "FK_TERM2" FOREIGN KEY ("ID_TERM")
	  REFERENCES  "CABS_TERM" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "CABS_TERM_PROC" ADD CONSTRAINT "FK_TERM_PROC" FOREIGN KEY ("ID_TERM")
	  REFERENCES  "CABS_TERM" ("ID") ENABLE
/
ALTER TABLE  "CABS_TERM_ORIGEN" ADD CONSTRAINT "PK_TERM_OR1" FOREIGN KEY ("ID_CORR")
	  REFERENCES  "CABS_CORR_D" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS_M" ADD FOREIGN KEY ("DFISCAL")
	  REFERENCES  "CLI_DFISCAL" ("ID") ENABLE
/
ALTER TABLE  "CABS_PEDIDOS" ADD FOREIGN KEY ("FAC_TO")
	  REFERENCES  "CLI_DFISCAL" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_C" ADD FOREIGN KEY ("ART_1")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_C" ADD FOREIGN KEY ("ART_2")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_C" ADD FOREIGN KEY ("ART_3")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_C" ADD FOREIGN KEY ("CAL_1")
	  REFERENCES  "ART_CALIDAD" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_C" ADD FOREIGN KEY ("CAL_2")
	  REFERENCES  "ART_CALIDAD" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_C" ADD FOREIGN KEY ("CAL_3")
	  REFERENCES  "ART_CALIDAD" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_D" ADD FOREIGN KEY ("ART_1")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_D" ADD FOREIGN KEY ("ART_2")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_D" ADD FOREIGN KEY ("ART_3")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_CORR_D" ADD FOREIGN KEY ("CALIDAD")
	  REFERENCES  "ART_CALIDAD" ("ID") ENABLE
/
ALTER TABLE  "CABS_TERM_ORIGEN" ADD FOREIGN KEY ("ART")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_TERM" ADD FOREIGN KEY ("ART")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_TERM" ADD FOREIGN KEY ("PEDIDO")
	  REFERENCES  "CABS_PEDIDOS" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS" ADD FOREIGN KEY ("PEDIDO")
	  REFERENCES  "CABS_PEDIDOS" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS" ADD FOREIGN KEY ("ART")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS_2" ADD FOREIGN KEY ("ART")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS_2" ADD FOREIGN KEY ("PEDIDO")
	  REFERENCES  "CABS_PEDIDOS" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS_M" ADD FOREIGN KEY ("CLIENTE")
	  REFERENCES  "CLI" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS_M" ADD FOREIGN KEY ("DEPOSITO")
	  REFERENCES  "CLI_DEPOSITO" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS_M2" ADD FOREIGN KEY ("DEPOSITO")
	  REFERENCES  "CLI_DEPOSITO" ("ID") ENABLE
/
ALTER TABLE  "CABS_ENTREGAS_M2" ADD FOREIGN KEY ("CLIENTE")
	  REFERENCES  "CLI" ("ID") ENABLE
/
ALTER TABLE  "CABS_PEDIDOS" ADD FOREIGN KEY ("ART_ID")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "CABS_PEDIDOS" ADD FOREIGN KEY ("CLIENTE")
	  REFERENCES  "CLI" ("ID") ENABLE
/
ALTER TABLE  "CABS_PEDIDOS" ADD FOREIGN KEY ("ENT_EN")
	  REFERENCES  "CLI_DEPOSITO" ("ID") ENABLE
/
