CREATE TABLE  "CLI_ESTADO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(20), 
	 CONSTRAINT "CLI_ESTADO_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CLI_VENDEDOR" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(200) NOT NULL ENABLE, 
	"APELLIDO" VARCHAR2(200), 
	"TELEFONO" VARCHAR2(200), 
	"MOVIL" VARCHAR2(200), 
	"EMAIL" VARCHAR2(200), 
	"DIRECCION" VARCHAR2(200), 
	"CREATED_FEC" DATE, 
	"CREATED_BY" VARCHAR2(200), 
	"UPDATED_FEC" DATE, 
	"UPDATED_BY" VARCHAR2(200), 
	 CONSTRAINT "CLI_VENDEDOR_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CLI" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(200) NOT NULL ENABLE, 
	"VENDEDOR" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"KEYWORD" VARCHAR2(400), 
	"ESTADO" NUMBER(*,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_FEC" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(200) NOT NULL ENABLE, 
	"UPDATED_FEC" DATE, 
	"UPDATED_BY" VARCHAR2(200), 
	"AJ_FLT" NUMBER DEFAULT NULL, 
	"AJ_COMISION" NUMBER DEFAULT 0, 
	"FEC_ULT_PEDIDO" DATE, 
	"AJ_IIBB" NUMBER(*,4), 
	"AJ_COTIZ" NUMBER, 
	"CONTENT" BLOB, 
	"MIMETYPE" VARCHAR2(48), 
	"FILENAME" VARCHAR2(400), 
	"LASTUPDATED" DATE, 
	 CONSTRAINT "CLI_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CLI_CONTACTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CLIENTE" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(200), 
	"APELLIDO" VARCHAR2(200), 
	"TELEFONO" VARCHAR2(200), 
	"MOVIL" VARCHAR2(200), 
	"EMAIL" VARCHAR2(200), 
	"DIRECCION" VARCHAR2(200), 
	"CARGO" VARCHAR2(200), 
	 CONSTRAINT "CLI_CONTACTO_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CLI_DEPOSITO" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_CLIENTE" NUMBER(*,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(200 CHAR), 
	"DIRECCION" VARCHAR2(400 CHAR), 
	"HORARIO" VARCHAR2(200 CHAR), 
	"CONTACTO" VARCHAR2(400 CHAR), 
	"OBSERVACIONES" VARCHAR2(400 CHAR), 
	"STREET_NUMBER" VARCHAR2(20), 
	"ROUTE" VARCHAR2(100), 
	"LOCALITY" VARCHAR2(100), 
	"ADMINISTRATIVE_AREA_LEVEL_1" VARCHAR2(50), 
	"POSTAL_CODE" VARCHAR2(20), 
	"COUNTRY" VARCHAR2(20), 
	"LAT" VARCHAR2(50), 
	"LNG" VARCHAR2(50), 
	"CREATED_FEC" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(200) NOT NULL ENABLE, 
	"UPDATED_FEC" DATE, 
	"UPDATED_BY" VARCHAR2(200), 
	 CONSTRAINT "CLI_DEPOSITO_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CLI_DFISCAL" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_CLIENTE" NUMBER(*,0) NOT NULL ENABLE, 
	"RAZON_SOCIAL" VARCHAR2(200 CHAR), 
	"CUIT" VARCHAR2(200 CHAR), 
	"DOMICILIO" VARCHAR2(200 CHAR), 
	"CIUDAD" VARCHAR2(200), 
	"CP" VARCHAR2(20), 
	"PROVINCIA" VARCHAR2(200), 
	"CREATED_FEC" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(200) NOT NULL ENABLE, 
	"UPDATED_FEC" DATE, 
	"UPDATED_BY" VARCHAR2(200), 
	"IMP_IIBB" NUMBER, 
	"IMP_IVA" NUMBER, 
	 CONSTRAINT "VC_CLIENTE_D_FISCAL_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "CLI_IIBB" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CUIT" VARCHAR2(20), 
	"DESDE" DATE, 
	"HASTA" DATE, 
	"VALOR" NUMBER, 
	 CONSTRAINT "CLI_IIBB_PK" PRIMARY KEY ("ID") ENABLE
   )
/
ALTER TABLE  "CLI" ADD CONSTRAINT "CLI_FK1" FOREIGN KEY ("VENDEDOR")
	  REFERENCES  "CLI_VENDEDOR" ("ID") ENABLE
/
ALTER TABLE  "CLI" ADD CONSTRAINT "CLI_FK2" FOREIGN KEY ("ESTADO")
	  REFERENCES  "CLI_ESTADO" ("ID") ENABLE
/
ALTER TABLE  "CLI_DFISCAL" ADD CONSTRAINT "FK_CLI_DFISCAL" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES  "CLI" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "CLI_DEPOSITO" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES  "CLI" ("ID") ENABLE
/
ALTER TABLE  "CLI_CONTACTO" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES  "CLI" ("ID") ENABLE
/
