CREATE TABLE  "COTIZ_ART" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CLIENTE" NUMBER, 
	"CLIENTE" VARCHAR2(20), 
	"ID_ART" NUMBER, 
	"CODIGO" VARCHAR2(20), 
	"TIPO" NUMBER, 
	"LARGO" NUMBER, 
	"ANCHO" NUMBER, 
	"ALTO" NUMBER, 
	"PLARGO" NUMBER, 
	"PANCHO" NUMBER, 
	"CALIDAD" NUMBER, 
	"AJ_COMISION" NUMBER, 
	"CANT" NUMBER, 
	"PRECIO_CALIDAD" NUMBER, 
	"AJ_COTIZ" NUMBER, 
	"AJ_PRECIO" NUMBER, 
	"PRECIO" NUMBER, 
	"OBS" VARCHAR2(200), 
	"STATUS" NUMBER, 
	"CREATED_BY" VARCHAR2(20), 
	"SUPERFICIE" NUMBER, 
	"DESDE" DATE, 
	"HASTA" DATE, 
	"VENDEDOR" NUMBER, 
	 CONSTRAINT "COTIZ_ART_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "COTIZ_PAPEL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TIPO_PAPEL" NUMBER, 
	"PRECIO" NUMBER, 
	"DESDE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_FEC" DATE, 
	"HASTA" DATE, 
	 CONSTRAINT "COTIZ_PAPEL_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "COTIZ_PARAM" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PARAM" VARCHAR2(20), 
	"UNIDAD" VARCHAR2(20), 
	"VALOR" NUMBER, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_FEC" DATE, 
	"COD" VARCHAR2(3), 
	"DESDE" DATE, 
	"HASTA" DATE, 
	 CONSTRAINT "COTIZ_PARAM_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "COTIZ_PLANCHA_PROV" 
   (	"ID" NUMBER, 
	"CALIDAD" NUMBER, 
	"PRECIO" NUMBER, 
	"DESDE" DATE, 
	"HASTA" DATE
   )
/
ALTER TABLE  "COTIZ_ART" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES  "CLI" ("ID") ENABLE
/
ALTER TABLE  "COTIZ_ART" ADD FOREIGN KEY ("ID_ART")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "COTIZ_ART" ADD FOREIGN KEY ("CALIDAD")
	  REFERENCES  "ART_CALIDAD" ("ID") ENABLE
/
ALTER TABLE  "COTIZ_PAPEL" ADD FOREIGN KEY ("TIPO_PAPEL")
	  REFERENCES  "BOB_TIPO" ("ID") ENABLE
/
ALTER TABLE  "COTIZ_PLANCHA_PROV" ADD FOREIGN KEY ("CALIDAD")
	  REFERENCES  "ART_CALIDAD" ("ID") ENABLE
/
