CREATE OR REPLACE FORCE VIEW "V1_REMITOS" ("ID", "FECHA", "MES", "CLIENTE", "DFISCAL", "IIBB", "SUBT_NETO", "SUBT_IVA", "SUBT_IIBB", "TOTAL", "REMITO", "STATUS", "FACTURAS", "SALDO_FACTURADO") AS 
  select ID,       FECHA, TO_CHAR(FECHA,'YYYY-MM') MES,       CLIENTE,  DFISCAL,       IIBB,       SUBT_NETO,       SUBT_IVA,       SUBT_IIBB,       TOTAL,       REMITO,            STATUS,
  (SELECT LISTAGG(F.NRO_CAB,',')within group(order by y.id_factura) 		
   FROM cabX_fact_ENTREGA Y,CABS_FACTURAS F      WHERE y.id_ENTREGA  = M.id and y.id_factura = f.id) FACTURAS,  
   (SELECT SUM(IMPORTE) FROM CABX_FACT_ENTREGA WHERE ID_ENTREGA = M.ID) SALDO_FACTURADO  
   
   from CABS_ENTREGAS_M M